-- =============================================================================
-- FAST - Oracle Database Init (tables only)
-- Use in dev and prod Oracle. Run once as schema owner. Oracle 12c+ (IDENTITY).
-- Data: insert via UI or by admin (no seed in this script).
-- =============================================================================

-- USERS (no password; auth via BAM/LDAP)
CREATE TABLE users (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50) NOT NULL,
    brid            VARCHAR2(20),
    email           VARCHAR2(100) NOT NULL,
    full_name       VARCHAR2(100) NOT NULL,
    role            VARCHAR2(30) NOT NULL,
    region          VARCHAR2(10),
    active          NUMBER(1) DEFAULT 1 NOT NULL,
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_brid UNIQUE (brid),
    CONSTRAINT chk_users_active CHECK (active IN (0, 1))
);
CREATE INDEX idx_users_active ON users(active);

-- APPLICATIONS
CREATE TABLE applications (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    code            VARCHAR2(50),
    description     VARCHAR2(500),
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date    TIMESTAMP,
    CONSTRAINT uq_applications_name UNIQUE (name)
);
CREATE INDEX idx_applications_name ON applications(name);

-- USER_APPLICATION (many-to-many)
CREATE TABLE user_application (
    user_id         NUMBER(19) NOT NULL,
    application_id  NUMBER(19) NOT NULL,
    PRIMARY KEY (user_id, application_id),
    CONSTRAINT fk_ua_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ua_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
);
CREATE INDEX idx_user_application_app ON user_application(application_id);

-- FAST_PROBLEM (no regional_code; use fast_problem_region)
CREATE TABLE fast_problem (
    id                          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    servicenow_incident_number  VARCHAR2(20),
    servicenow_problem_number   VARCHAR2(20),
    pbt_id                      VARCHAR2(30),
    title                       VARCHAR2(255) NOT NULL,
    description                 CLOB,
    user_impact_count           NUMBER(10) DEFAULT 0,
    affected_application       VARCHAR2(100),
    request_number             VARCHAR2(100),
    anticipated_benefits        CLOB,
    classification              VARCHAR2(10) DEFAULT 'A',
    ticket_age_days             NUMBER(10) DEFAULT 0,
    rag_status                  VARCHAR2(5) DEFAULT 'G',
    status_indicator            VARCHAR2(10) DEFAULT 'R16',
    status                      VARCHAR2(30) DEFAULT 'NEW',
    priority_score              BINARY_DOUBLE DEFAULT 0.0,
    priority                    NUMBER(10) DEFAULT 3,
    target_resolution_hours     NUMBER(10) DEFAULT 4,
    api_integration_status      VARCHAR2(20) DEFAULT 'MANUAL_ENTRY',
    root_cause                  CLOB,
    workaround                  CLOB,
    permanent_fix               CLOB,
    created_by                  VARCHAR2(50) NOT NULL,
    assigned_to                 VARCHAR2(50),
    assignment_group            VARCHAR2(100),
    btb_tech_lead_username      VARCHAR2(50),
    confluence_link             VARCHAR2(500),
    created_date                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_date               TIMESTAMP,
    deleted                     NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_fast_problem_deleted CHECK (deleted IN (0, 1))
);
CREATE INDEX idx_fast_problem_status ON fast_problem(status);
CREATE INDEX idx_fast_problem_classification ON fast_problem(classification);
CREATE INDEX idx_fast_problem_rag_status ON fast_problem(rag_status);
CREATE INDEX idx_fast_problem_pbt_id ON fast_problem(pbt_id);
CREATE INDEX idx_fast_problem_inc_number ON fast_problem(servicenow_incident_number);
CREATE INDEX idx_fast_problem_prb_number ON fast_problem(servicenow_problem_number);
CREATE INDEX idx_fast_problem_created_date ON fast_problem(created_date);
CREATE INDEX idx_fast_problem_deleted ON fast_problem(deleted);
CREATE INDEX idx_fast_problem_deleted_created ON fast_problem(deleted, created_date);
CREATE INDEX idx_fast_problem_affected_app ON fast_problem(affected_application);
CREATE INDEX idx_fast_problem_request_number ON fast_problem(request_number);
CREATE INDEX idx_fast_problem_resolved_date ON fast_problem(resolved_date);
CREATE INDEX idx_fast_problem_updated_date ON fast_problem(updated_date);
CREATE INDEX idx_fast_problem_assigned_to ON fast_problem(assigned_to);

-- FAST_PROBLEM_APPLICATION (ticket impacts one-to-many applications)
CREATE TABLE fast_problem_application (
    fast_problem_id NUMBER(19) NOT NULL,
    application_id  NUMBER(19) NOT NULL,
    PRIMARY KEY (fast_problem_id, application_id),
    CONSTRAINT fk_fpa_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id) ON DELETE CASCADE,
    CONSTRAINT fk_fpa_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
);
CREATE INDEX idx_fast_problem_application_app ON fast_problem_application(application_id);

-- APPROVAL_RECORD (one record per role: REVIEWER, APPROVER, RTB_OWNER; anyone with that role can approve)
CREATE TABLE approval_record (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    approval_role   VARCHAR2(20) NOT NULL,
    reviewer_name   VARCHAR2(100),
    reviewer_email  VARCHAR2(100),
    decision        VARCHAR2(20) DEFAULT 'PENDING',
    comments        CLOB,
    decision_date   TIMESTAMP,
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_approval_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);
CREATE INDEX idx_approval_problem_id ON approval_record(fast_problem_id);
CREATE INDEX idx_approval_decision ON approval_record(decision);
CREATE INDEX idx_approval_role ON approval_record(approval_role);

-- KNOWLEDGE_ARTICLE
CREATE TABLE knowledge_article (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19),
    title           VARCHAR2(255) NOT NULL,
    root_cause      CLOB,
    workaround      CLOB,
    permanent_fix   CLOB,
    category        VARCHAR2(50),
    status          VARCHAR2(20) DEFAULT 'DRAFT',
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    published_date  TIMESTAMP,
    CONSTRAINT uq_knowledge_fast_problem_id UNIQUE (fast_problem_id),
    CONSTRAINT fk_knowledge_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);
CREATE INDEX idx_knowledge_status ON knowledge_article(status);
CREATE INDEX idx_knowledge_created_date ON knowledge_article(created_date);

-- INCIDENT_LINK
CREATE TABLE incident_link (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    incident_number VARCHAR2(20) NOT NULL,
    link_type       VARCHAR2(20) DEFAULT 'RELATED_TO',
    description     VARCHAR2(500),
    linked_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_incident_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);
CREATE INDEX idx_incident_link_problem_id ON incident_link(fast_problem_id);
CREATE INDEX idx_incident_link_number ON incident_link(incident_number);

-- AUDIT_LOG
CREATE TABLE audit_log (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    action          VARCHAR2(50) NOT NULL,
    performed_by    VARCHAR2(50) NOT NULL,
    field_changed   VARCHAR2(50),
    old_value       VARCHAR2(500),
    new_value       VARCHAR2(500),
    timestamp       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);
CREATE INDEX idx_audit_problem_id ON audit_log(fast_problem_id);
CREATE INDEX idx_audit_timestamp ON audit_log(timestamp);
CREATE INDEX idx_audit_problem_timestamp ON audit_log(fast_problem_id, timestamp);

-- FAST_PROBLEM_REGION
CREATE TABLE fast_problem_region (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    regional_code   VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_fpr_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id) ON DELETE CASCADE,
    CONSTRAINT uq_fast_problem_region UNIQUE (fast_problem_id, regional_code)
);
CREATE INDEX idx_fast_problem_region_code ON fast_problem_region(regional_code);
CREATE INDEX idx_fast_problem_region_problem_id ON fast_problem_region(fast_problem_id);

-- FAST_PROBLEM_PROPERTY
CREATE TABLE fast_problem_property (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    property_key    VARCHAR2(255) NOT NULL,
    property_value  CLOB,
    CONSTRAINT fk_fpp_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id) ON DELETE CASCADE,
    CONSTRAINT uq_fast_problem_property UNIQUE (fast_problem_id, property_key)
);
CREATE INDEX idx_fast_problem_property_problem_id ON fast_problem_property(fast_problem_id);

-- FAST_PROBLEM_LINK
CREATE TABLE fast_problem_link (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    label           VARCHAR2(100) NOT NULL,
    url             VARCHAR2(2000) NOT NULL,
    link_type       VARCHAR2(20) DEFAULT 'OTHER',
    CONSTRAINT fk_fpl_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id) ON DELETE CASCADE
);
CREATE INDEX idx_fast_problem_link_problem_id ON fast_problem_link(fast_problem_id);

-- TICKET_COMMENT
CREATE TABLE ticket_comment (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    author_username VARCHAR2(50) NOT NULL,
    comment_text    CLOB NOT NULL,
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tc_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id) ON DELETE CASCADE
);
CREATE INDEX idx_ticket_comment_problem_id ON ticket_comment(fast_problem_id);

-- APP_SETTINGS
CREATE TABLE app_settings (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    setting_key     VARCHAR2(100) NOT NULL UNIQUE,
    setting_value   CLOB,
    description     VARCHAR2(255)
);
CREATE INDEX idx_app_settings_key ON app_settings(setting_key);

COMMIT;
