-- Migration: add DQ reference + impacted user groups support.
-- Run on existing H2 or Oracle DBs. New installs use init-h2.sql / init-oracle.sql.

-- H2
ALTER TABLE fast_problem ADD COLUMN IF NOT EXISTS dq_reference VARCHAR(100);
ALTER TABLE fast_problem ADD COLUMN IF NOT EXISTS impacted_user_group_notes CLOB;
CREATE INDEX IF NOT EXISTS idx_fast_problem_dq_reference ON fast_problem(dq_reference);

CREATE TABLE IF NOT EXISTS user_group (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(50),
    description VARCHAR(500),
    active BOOLEAN DEFAULT TRUE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_group_name ON user_group(name);
CREATE INDEX IF NOT EXISTS idx_user_group_active ON user_group(active);

CREATE TABLE IF NOT EXISTS fast_problem_user_group (
    fast_problem_id BIGINT NOT NULL,
    user_group_id BIGINT NOT NULL,
    PRIMARY KEY (fast_problem_id, user_group_id),
    CONSTRAINT fk_fpug_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id) ON DELETE CASCADE,
    CONSTRAINT fk_fpug_user_group FOREIGN KEY (user_group_id) REFERENCES user_group(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_fast_problem_user_group_group ON fast_problem_user_group(user_group_id);

MERGE INTO app_settings (setting_key, setting_value, description)
KEY (setting_key)
VALUES ('acceptedTicketEmailEnabled', 'false', 'Send accepted-ticket notification emails to TECH_LEAD users');

-- Oracle (uncomment and run separately if using Oracle):
-- ALTER TABLE fast_problem ADD (dq_reference VARCHAR2(100));
-- ALTER TABLE fast_problem ADD (impacted_user_group_notes CLOB);
-- CREATE INDEX idx_fast_problem_dq_reference ON fast_problem(dq_reference);
--
-- CREATE TABLE user_group (
--     id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     name VARCHAR2(100) NOT NULL,
--     code VARCHAR2(50),
--     description VARCHAR2(500),
--     active NUMBER(1) DEFAULT 1 NOT NULL,
--     created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_date TIMESTAMP,
--     CONSTRAINT uq_user_group_name UNIQUE (name),
--     CONSTRAINT chk_user_group_active CHECK (active IN (0, 1))
-- );
-- CREATE INDEX idx_user_group_name ON user_group(name);
-- CREATE INDEX idx_user_group_active ON user_group(active);
--
-- CREATE TABLE fast_problem_user_group (
--     fast_problem_id NUMBER(19) NOT NULL,
--     user_group_id NUMBER(19) NOT NULL,
--     PRIMARY KEY (fast_problem_id, user_group_id),
--     CONSTRAINT fk_fpug_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id) ON DELETE CASCADE,
--     CONSTRAINT fk_fpug_user_group FOREIGN KEY (user_group_id) REFERENCES user_group(id) ON DELETE CASCADE
-- );
-- CREATE INDEX idx_fast_problem_user_group_group ON fast_problem_user_group(user_group_id);
--
-- MERGE INTO app_settings s
-- USING (SELECT 'acceptedTicketEmailEnabled' AS setting_key, 'false' AS setting_value, 'Send accepted-ticket notification emails to TECH_LEAD users' AS description FROM dual) src
-- ON (s.setting_key = src.setting_key)
-- WHEN NOT MATCHED THEN
--   INSERT (setting_key, setting_value, description) VALUES (src.setting_key, src.setting_value, src.description);
--
-- COMMIT;
