-- Migration: add interview schedule capture (sheet header + hourly rows).
-- Run on existing H2 or Oracle DBs. New installs use init-h2.sql / init-oracle.sql.

-- H2
CREATE TABLE IF NOT EXISTS interview_schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    business_area VARCHAR(150),
    pc_director VARCHAR(150),
    product_controller VARCHAR(150),
    named_pnls VARCHAR(500),
    location VARCHAR(150),
    interviewed_by VARCHAR(150),
    interview_date DATE,
    created_by VARCHAR(50) NOT NULL,
    updated_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_interview_schedule_date ON interview_schedule(interview_date);
CREATE INDEX IF NOT EXISTS idx_interview_schedule_created_date ON interview_schedule(created_date);

CREATE TABLE IF NOT EXISTS interview_schedule_entry (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    interview_schedule_id BIGINT NOT NULL,
    time_slot VARCHAR(5) NOT NULL,
    display_order INTEGER NOT NULL,
    business_function CLOB,
    applications_used CLOB,
    process_improvements CLOB,
    tech_issues_to_resolve CLOB,
    ticket_raised CLOB,
    CONSTRAINT fk_interview_schedule_entry_schedule FOREIGN KEY (interview_schedule_id) REFERENCES interview_schedule(id) ON DELETE CASCADE,
    CONSTRAINT uq_interview_schedule_entry_slot UNIQUE (interview_schedule_id, time_slot)
);
CREATE INDEX IF NOT EXISTS idx_interview_schedule_entry_schedule ON interview_schedule_entry(interview_schedule_id);
CREATE INDEX IF NOT EXISTS idx_interview_schedule_entry_order ON interview_schedule_entry(interview_schedule_id, display_order);

-- Oracle (uncomment and run separately if using Oracle):
-- CREATE TABLE interview_schedule (
--     id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     business_area   VARCHAR2(150),
--     pc_director     VARCHAR2(150),
--     product_controller VARCHAR2(150),
--     named_pnls      VARCHAR2(500),
--     location        VARCHAR2(150),
--     interviewed_by  VARCHAR2(150),
--     interview_date  DATE,
--     created_by      VARCHAR2(50) NOT NULL,
--     updated_by      VARCHAR2(50),
--     created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- CREATE INDEX idx_interview_schedule_date ON interview_schedule(interview_date);
-- CREATE INDEX idx_interview_schedule_created_date ON interview_schedule(created_date);
--
-- CREATE TABLE interview_schedule_entry (
--     id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--     interview_schedule_id NUMBER(19) NOT NULL,
--     time_slot           VARCHAR2(5) NOT NULL,
--     display_order       NUMBER(10) NOT NULL,
--     business_function   CLOB,
--     applications_used   CLOB,
--     process_improvements CLOB,
--     tech_issues_to_resolve CLOB,
--     ticket_raised       CLOB,
--     CONSTRAINT fk_interview_schedule_entry_schedule FOREIGN KEY (interview_schedule_id) REFERENCES interview_schedule(id) ON DELETE CASCADE,
--     CONSTRAINT uq_interview_schedule_entry_slot UNIQUE (interview_schedule_id, time_slot)
-- );
-- CREATE INDEX idx_interview_schedule_entry_schedule ON interview_schedule_entry(interview_schedule_id);
-- CREATE INDEX idx_interview_schedule_entry_order ON interview_schedule_entry(interview_schedule_id, display_order);
--
-- COMMIT;
