-- Minimal sample tickets (keep simple: 5 records)
INSERT INTO fast_problem (
    servicenow_incident_number,
    servicenow_problem_number,
    pbt_id,
    title,
    description,
    user_impact_count,
    affected_application,
    anticipated_benefits,
    classification,
    ticket_age_days,
    rag_status,
    status_indicator,
    status,
    priority_score,
    priority,
    target_resolution_hours,
    api_integration_status,
    root_cause,
    workaround,
    permanent_fix,
    created_by,
    assigned_to,
    assignment_group,
    btb_tech_lead_username,
    confluence_link,
    created_date,
    updated_date,
    resolved_date,
    deleted,
    archived
) VALUES
(
    'INC-FAST-1001',
    'PRB-FAST-2001',
    'PBT-4001',
    'MOTIF to RecFactory reconciliation variance',
    'Daily reconciliation shows mismatch for one AMER desk.',
    24,
    'RecFactory',
    'Reduce manual reconciliation effort.',
    'A',
    2,
    'G',
    'R16',
    'BACKLOG',
    14.0,
    2,
    4,
    'MANUAL_ENTRY',
    NULL,
    NULL,
    NULL,
    'admin',
    NULL,
    'AMER-Problem-Team',
    NULL,
    NULL,
    DATEADD('DAY', -2, CURRENT_TIMESTAMP),
    DATEADD('DAY', -2, CURRENT_TIMESTAMP),
    NULL,
    false,
    false
),
(
    'INC-FAST-1002',
    'PRB-FAST-2002',
    'PBT-4002',
    'SAP feed delay for month-end extract',
    'Month-end export is delayed due to source ingest lag.',
    8,
    'SAP',
    'Avoid reporting delays.',
    'R',
    4,
    'G',
    'R16',
    'ASSIGNED',
    6.0,
    3,
    8,
    'MANUAL_ENTRY',
    NULL,
    NULL,
    NULL,
    'admin',
    'pm',
    'EMEA-Problem-Team',
    NULL,
    NULL,
    DATEADD('DAY', -4, CURRENT_TIMESTAMP),
    DATEADD('DAY', -1, CURRENT_TIMESTAMP),
    NULL,
    false,
    false
),
(
    'INC-FAST-1003',
    'PRB-FAST-2003',
    'PBT-4003',
    'Workflow Engine alert rule tuning',
    'Alerting logic is noisy and requires threshold updates.',
    5,
    'Workflow Engine',
    'Improve signal quality for support.',
    'P',
    6,
    'G',
    'R16',
    'ACCEPTED',
    4.0,
    3,
    8,
    'MANUAL_ENTRY',
    NULL,
    NULL,
    NULL,
    'admin',
    'kostas',
    'AMER-Problem-Team',
    'prav',
    NULL,
    DATEADD('DAY', -6, CURRENT_TIMESTAMP),
    DATEADD('DAY', -1, CURRENT_TIMESTAMP),
    NULL,
    false,
    false
),
(
    'INC-FAST-1004',
    'PRB-FAST-2004',
    'PBT-4004',
    'Playpen access sync with FinPortal',
    'Some users are not syncing correctly after role updates.',
    12,
    'Playpen',
    'Reduce access-related tickets.',
    'A',
    9,
    'G',
    'R16',
    'IN_PROGRESS',
    9.0,
    2,
    6,
    'MANUAL_ENTRY',
    'Provisioning job mapping issue.',
    'Manual role refresh for impacted users.',
    NULL,
    'admin',
    'prav',
    'APAC-Problem-Team',
    'prav',
    'https://confluence.local/fast/playpen-sync',
    DATEADD('DAY', -9, CURRENT_TIMESTAMP),
    DATEADD('HOUR', -6, CURRENT_TIMESTAMP),
    NULL,
    false,
    false
),
(
    'INC-FAST-1005',
    'PRB-FAST-2005',
    'PBT-4005',
    'RADIAL extract format correction',
    'Download Center output schema mismatch fixed in latest run.',
    3,
    'RADIAL',
    'Stabilize downstream reporting loads.',
    'R',
    1,
    'G',
    'B16',
    'RESOLVED',
    2.0,
    4,
    4,
    'MANUAL_ENTRY',
    'Column ordering drift in export template.',
    'Use prior template while patch is deployed.',
    'Template mapping fixed and validated.',
    'admin',
    'pm',
    'EMEA-Problem-Team',
    'prav',
    NULL,
    DATEADD('DAY', -1, CURRENT_TIMESTAMP),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    false,
    false
);

INSERT INTO fast_problem_region (fast_problem_id, regional_code) VALUES
(1, 'AMER'),
(2, 'EMEA'),
(3, 'AMER'),
(4, 'APAC'),
(5, 'EMEA');

INSERT INTO fast_problem_application (fast_problem_id, application_id)
SELECT 1, id FROM applications WHERE code IN ('MOTIF', 'RECFACTORY');
INSERT INTO fast_problem_application (fast_problem_id, application_id)
SELECT 2, id FROM applications WHERE code IN ('SAP');
INSERT INTO fast_problem_application (fast_problem_id, application_id)
SELECT 3, id FROM applications WHERE code IN ('WORKFLOW_ENGINE');
INSERT INTO fast_problem_application (fast_problem_id, application_id)
SELECT 4, id FROM applications WHERE code IN ('PLAYPEN', 'FINPORTAL');
INSERT INTO fast_problem_application (fast_problem_id, application_id)
SELECT 5, id FROM applications WHERE code IN ('RADIAL', 'DOWNLOAD_CENTER');

INSERT INTO fast_problem_user_group (fast_problem_id, user_group_id)
SELECT 1, id FROM user_group WHERE code IN ('FIN_CTRL');
INSERT INTO fast_problem_user_group (fast_problem_id, user_group_id)
SELECT 4, id FROM user_group WHERE code IN ('OPS');

UPDATE fast_problem SET rag_status = 'A' WHERE ticket_age_days > 15 AND ticket_age_days <= 20 AND deleted = false;
UPDATE fast_problem SET rag_status = 'R' WHERE ticket_age_days > 20 AND deleted = false;
