-- 100 seed tickets (different applications and regions); regions in fast_problem_region below.
INSERT INTO fast_problem (servicenow_incident_number, servicenow_problem_number, pbt_id, title, description,
    user_impact_count, affected_application, anticipated_benefits, classification, ticket_age_days,
    status_indicator, status, priority_score, priority, target_resolution_hours, api_integration_status,
    root_cause, workaround, permanent_fix, created_by, assigned_to, assignment_group, confluence_link,
    created_date, updated_date, resolved_date, deleted) VALUES
('INC1001', 'PRB2001', 'PBT-3001', 'Issue in Payment Gateway - performance/outage #1', 'users reporting issues with Payment Gateway. Investigation required.', 2, 'Payment Gateway', 'Improved stability and user experience for Payment Gateway.', 'A', 1, 'R16', 'BACKLOG', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', NULL, DATEADD('DAY', -0, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_TIMESTAMP), NULL, false),
('INC1002', 'PRB2002', 'PBT-3002', 'Issue in Order Management - performance/outage #2', 'users reporting issues with Order Management. Investigation required.', 3, 'Order Management', 'Improved stability and user experience for Order Management.', 'R', 2, 'R16', 'ASSIGNED', 0.75, 3, 4, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2003', 'PBT-3003', 'Issue in Inventory System - performance/outage #3', 'users reporting issues with Inventory System. Investigation required.', 4, 'Inventory System', 'Improved stability and user experience for Inventory System.', 'P', 3, 'R16', 'IN_PROGRESS', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -0, CURRENT_TIMESTAMP), NULL, false),
('INC1004', NULL, 'PBT-3004', 'Issue in CRM - performance/outage #4', 'users reporting issues with CRM. Investigation required.', 5, 'CRM', 'Improved stability and user experience for CRM.', 'A', 4, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), NULL, false),
('INC1005', 'PRB2005', 'PBT-3005', 'Issue in HR Portal - performance/outage #5', 'users reporting issues with HR Portal. Investigation required.', 6, 'HR Portal', 'Improved stability and user experience for HR Portal.', 'R', 5, 'R16', 'FIX_IN_PROGRESS', 0.5, 2, 2, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-5', DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2006', 'PBT-3006', 'Issue in Finance Suite - performance/outage #6', 'users reporting issues with Finance Suite. Investigation required.', 7, 'Finance Suite', 'Improved stability and user experience for Finance Suite.', 'P', 6, 'R16', 'RESOLVED', 0.75, 3, 4, 'MANUAL_ENTRY', 'Root cause for ticket 6 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('HOUR', -2, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1007', 'PRB2007', 'PBT-3007', 'Issue in Shipping Service - performance/outage #7', 'users reporting issues with Shipping Service. Investigation required.', 8, 'Shipping Service', 'Improved stability and user experience for Shipping Service.', 'A', 7, 'R16', 'CLOSED', 1.0, 4, 8, 'MANUAL_ENTRY', 'Root cause for ticket 7 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -4, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1008', NULL, 'PBT-3008', 'Issue in Customer Support - performance/outage #8', 'users reporting issues with Customer Support. Investigation required.', 9, 'Customer Support', 'Improved stability and user experience for Customer Support.', 'R', 8, 'R16', 'BACKLOG', 0.25, 1, 24, 'API_SYNCED', NULL, NULL, NULL, 'admin', NULL, 'App Support', NULL, DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2009', 'PBT-3009', 'Issue in Analytics Dashboard - performance/outage #9', 'users reporting issues with Analytics Dashboard. Investigation required.', 10, 'Analytics Dashboard', 'Improved stability and user experience for Analytics Dashboard.', 'P', 9, 'R16', 'ASSIGNED', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -8, CURRENT_TIMESTAMP), DATEADD('DAY', -6, CURRENT_TIMESTAMP), NULL, false),
('INC1010', 'PRB2010', 'PBT-3010', 'Issue in Reporting Engine - performance/outage #10', 'users reporting issues with Reporting Engine. Investigation required.', 11, 'Reporting Engine', 'Improved stability and user experience for Reporting Engine.', 'A', 10, 'R16', 'IN_PROGRESS', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-10', DATEADD('DAY', -9, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_TIMESTAMP), NULL, false),
('INC1011', 'PRB2011', 'PBT-3011', 'Issue in Auth Service - performance/outage #11', 'users reporting issues with Auth Service. Investigation required.', 12, 'Auth Service', 'Improved stability and user experience for Auth Service.', 'R', 11, 'R16', 'ROOT_CAUSE_IDENTIFIED', 1.0, 4, 8, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -10, CURRENT_TIMESTAMP), DATEADD('DAY', -8, CURRENT_TIMESTAMP), NULL, false),
(NULL, NULL, 'PBT-3012', 'Issue in Notification Service - performance/outage #12', 'users reporting issues with Notification Service. Investigation required.', 13, 'Notification Service', 'Improved stability and user experience for Notification Service.', 'P', 12, 'R16', 'FIX_IN_PROGRESS', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -11, CURRENT_TIMESTAMP), DATEADD('DAY', -9, CURRENT_TIMESTAMP), NULL, false),
('INC1013', 'PRB2013', 'PBT-3013', 'Issue in Search Index - performance/outage #13', 'users reporting issues with Search Index. Investigation required.', 14, 'Search Index', 'Improved stability and user experience for Search Index.', 'A', 13, 'R16', 'RESOLVED', 0.5, 2, 2, 'MANUAL_ENTRY', 'Root cause for ticket 13 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1014', 'PRB2014', 'PBT-3014', 'Issue in API Gateway - performance/outage #14', 'users reporting issues with API Gateway. Investigation required.', 15, 'API Gateway', 'Improved stability and user experience for API Gateway.', 'R', 14, 'R16', 'CLOSED', 0.75, 3, 4, 'API_SYNCED', 'Root cause for ticket 14 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'App Support', NULL, DATEADD('HOUR', -2, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
(NULL, 'PRB2015', 'PBT-3015', 'Issue in Config Service - performance/outage #15', 'users reporting issues with Config Service. Investigation required.', 16, 'Config Service', 'Improved stability and user experience for Config Service.', 'P', 15, 'R16', 'BACKLOG', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', 'https://wiki.example.com/ticket-15', DATEADD('DAY', -14, CURRENT_TIMESTAMP), DATEADD('DAY', -12, CURRENT_TIMESTAMP), NULL, false),
('INC1016', NULL, 'PBT-3016', 'Issue in Payment Gateway - performance/outage #16', 'users reporting issues with Payment Gateway. Investigation required.', 17, 'Payment Gateway', 'Improved stability and user experience for Payment Gateway.', 'A', 16, 'R16', 'ASSIGNED', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -15, CURRENT_TIMESTAMP), DATEADD('DAY', -13, CURRENT_TIMESTAMP), NULL, false),
('INC1017', 'PRB2017', 'PBT-3017', 'Issue in Order Management - performance/outage #17', 'users reporting issues with Order Management. Investigation required.', 18, 'Order Management', 'Improved stability and user experience for Order Management.', 'R', 17, 'R16', 'IN_PROGRESS', 0.5, 2, 2, 'API_SYNCED', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -16, CURRENT_TIMESTAMP), DATEADD('DAY', -14, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2018', 'PBT-3018', 'Issue in Inventory System - performance/outage #18', 'users reporting issues with Inventory System. Investigation required.', 19, 'Inventory System', 'Improved stability and user experience for Inventory System.', 'P', 18, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -17, CURRENT_TIMESTAMP), DATEADD('DAY', -15, CURRENT_TIMESTAMP), NULL, false),
('INC1019', 'PRB2019', 'PBT-3019', 'Issue in CRM - performance/outage #19', 'users reporting issues with CRM. Investigation required.', 20, 'CRM', 'Improved stability and user experience for CRM.', 'A', 19, 'R16', 'FIX_IN_PROGRESS', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -18, CURRENT_TIMESTAMP), DATEADD('DAY', -16, CURRENT_TIMESTAMP), NULL, false),
('INC1020', NULL, 'PBT-3020', 'Issue in HR Portal - performance/outage #20', 'users reporting issues with HR Portal. Investigation required.', 21, 'HR Portal', 'Improved stability and user experience for HR Portal.', 'R', 20, 'R16', 'RESOLVED', 0.25, 1, 24, 'API_SYNCED', 'Root cause for ticket 20 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-20', DATEADD('HOUR', -12, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
(NULL, 'PRB2021', 'PBT-3021', 'Issue in Finance Suite - performance/outage #21', 'users reporting issues with Finance Suite. Investigation required.', 22, 'Finance Suite', 'Improved stability and user experience for Finance Suite.', 'P', 21, 'R16', 'CLOSED', 0.5, 2, 2, 'MANUAL_ENTRY', 'Root cause for ticket 21 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1022', 'PRB2022', 'PBT-3022', 'Issue in Shipping Service - performance/outage #22', 'users reporting issues with Shipping Service. Investigation required.', 23, 'Shipping Service', 'Improved stability and user experience for Shipping Service.', 'A', 22, 'R16', 'BACKLOG', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'App Support', NULL, DATEADD('DAY', -21, CURRENT_TIMESTAMP), DATEADD('DAY', -19, CURRENT_TIMESTAMP), NULL, false),
('INC1023', 'PRB2023', 'PBT-3023', 'Issue in Customer Support - performance/outage #23', 'users reporting issues with Customer Support. Investigation required.', 24, 'Customer Support', 'Improved stability and user experience for Customer Support.', 'R', 23, 'R16', 'ASSIGNED', 1.0, 4, 8, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -22, CURRENT_TIMESTAMP), DATEADD('DAY', -20, CURRENT_TIMESTAMP), NULL, false),
(NULL, NULL, 'PBT-3024', 'Issue in Analytics Dashboard - performance/outage #24', 'users reporting issues with Analytics Dashboard. Investigation required.', 25, 'Analytics Dashboard', 'Improved stability and user experience for Analytics Dashboard.', 'P', 24, 'R16', 'IN_PROGRESS', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -23, CURRENT_TIMESTAMP), DATEADD('DAY', -21, CURRENT_TIMESTAMP), NULL, false),
('INC1025', 'PRB2025', 'PBT-3025', 'Issue in Reporting Engine - performance/outage #25', 'users reporting issues with Reporting Engine. Investigation required.', 26, 'Reporting Engine', 'Improved stability and user experience for Reporting Engine.', 'A', 25, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-25', DATEADD('DAY', -24, CURRENT_TIMESTAMP), DATEADD('DAY', -22, CURRENT_TIMESTAMP), NULL, false),
('INC1026', 'PRB2026', 'PBT-3026', 'Issue in Auth Service - performance/outage #26', 'users reporting issues with Auth Service. Investigation required.', 27, 'Auth Service', 'Improved stability and user experience for Auth Service.', 'R', 26, 'R16', 'FIX_IN_PROGRESS', 0.75, 3, 4, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -25, CURRENT_TIMESTAMP), DATEADD('DAY', -23, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2027', 'PBT-3027', 'Issue in Notification Service - performance/outage #27', 'users reporting issues with Notification Service. Investigation required.', 28, 'Notification Service', 'Improved stability and user experience for Notification Service.', 'P', 27, 'R16', 'RESOLVED', 1.0, 4, 8, 'MANUAL_ENTRY', 'Root cause for ticket 27 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -5, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1028', NULL, 'PBT-3028', 'Issue in Search Index - performance/outage #28', 'users reporting issues with Search Index. Investigation required.', 29, 'Search Index', 'Improved stability and user experience for Search Index.', 'A', 28, 'R16', 'CLOSED', 0.25, 1, 24, 'MANUAL_ENTRY', 'Root cause for ticket 28 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'App Support', NULL, DATEADD('HOUR', -18, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1029', 'PRB2029', 'PBT-3029', 'Issue in API Gateway - performance/outage #29', 'users reporting issues with API Gateway. Investigation required.', 30, 'API Gateway', 'Improved stability and user experience for API Gateway.', 'R', 29, 'R16', 'BACKLOG', 0.5, 2, 2, 'API_SYNCED', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', NULL, DATEADD('DAY', -28, CURRENT_TIMESTAMP), DATEADD('DAY', -26, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2030', 'PBT-3030', 'Issue in Config Service - performance/outage #30', 'users reporting issues with Config Service. Investigation required.', 31, 'Config Service', 'Improved stability and user experience for Config Service.', 'P', 0, 'R16', 'ASSIGNED', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-30', DATEADD('DAY', -29, CURRENT_TIMESTAMP), DATEADD('DAY', -27, CURRENT_TIMESTAMP), NULL, false),
('INC1031', 'PRB2031', 'PBT-3031', 'Issue in Payment Gateway - performance/outage #31', 'users reporting issues with Payment Gateway. Investigation required.', 32, 'Payment Gateway', 'Improved stability and user experience for Payment Gateway.', 'A', 1, 'R16', 'IN_PROGRESS', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -30, CURRENT_TIMESTAMP), DATEADD('DAY', -28, CURRENT_TIMESTAMP), NULL, false),
('INC1032', NULL, 'PBT-3032', 'Issue in Order Management - performance/outage #32', 'users reporting issues with Order Management. Investigation required.', 33, 'Order Management', 'Improved stability and user experience for Order Management.', 'R', 2, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.25, 1, 24, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -31, CURRENT_TIMESTAMP), DATEADD('DAY', -29, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2033', 'PBT-3033', 'Issue in Inventory System - performance/outage #33', 'users reporting issues with Inventory System. Investigation required.', 34, 'Inventory System', 'Improved stability and user experience for Inventory System.', 'P', 3, 'R16', 'FIX_IN_PROGRESS', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -32, CURRENT_TIMESTAMP), DATEADD('DAY', -30, CURRENT_TIMESTAMP), NULL, false),
('INC1034', 'PRB2034', 'PBT-3034', 'Issue in CRM - performance/outage #34', 'users reporting issues with CRM. Investigation required.', 35, 'CRM', 'Improved stability and user experience for CRM.', 'A', 4, 'R16', 'RESOLVED', 0.75, 3, 4, 'MANUAL_ENTRY', 'Root cause for ticket 34 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('HOUR', -2, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1035', 'PRB2035', 'PBT-3035', 'Issue in HR Portal - performance/outage #35', 'users reporting issues with HR Portal. Investigation required.', 36, 'HR Portal', 'Improved stability and user experience for HR Portal.', 'R', 5, 'R16', 'CLOSED', 1.0, 4, 8, 'API_SYNCED', 'Root cause for ticket 35 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-35', DATEADD('HOUR', -6, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
(NULL, NULL, 'PBT-3036', 'Issue in Finance Suite - performance/outage #36', 'users reporting issues with Finance Suite. Investigation required.', 37, 'Finance Suite', 'Improved stability and user experience for Finance Suite.', 'P', 6, 'R16', 'BACKLOG', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'App Support', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP), DATEADD('DAY', -33, CURRENT_TIMESTAMP), NULL, false),
('INC1037', 'PRB2037', 'PBT-3037', 'Issue in Shipping Service - performance/outage #37', 'users reporting issues with Shipping Service. Investigation required.', 38, 'Shipping Service', 'Improved stability and user experience for Shipping Service.', 'A', 7, 'R16', 'ASSIGNED', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -36, CURRENT_TIMESTAMP), DATEADD('DAY', -34, CURRENT_TIMESTAMP), NULL, false),
('INC1038', 'PRB2038', 'PBT-3038', 'Issue in Customer Support - performance/outage #38', 'users reporting issues with Customer Support. Investigation required.', 39, 'Customer Support', 'Improved stability and user experience for Customer Support.', 'R', 8, 'R16', 'IN_PROGRESS', 0.75, 3, 4, 'API_SYNCED', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -37, CURRENT_TIMESTAMP), DATEADD('DAY', -35, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2039', 'PBT-3039', 'Issue in Analytics Dashboard - performance/outage #39', 'users reporting issues with Analytics Dashboard. Investigation required.', 40, 'Analytics Dashboard', 'Improved stability and user experience for Analytics Dashboard.', 'P', 9, 'R16', 'ROOT_CAUSE_IDENTIFIED', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -38, CURRENT_TIMESTAMP), DATEADD('DAY', -36, CURRENT_TIMESTAMP), NULL, false),
('INC1040', NULL, 'PBT-3040', 'Issue in Reporting Engine - performance/outage #40', 'users reporting issues with Reporting Engine. Investigation required.', 41, 'Reporting Engine', 'Improved stability and user experience for Reporting Engine.', 'A', 10, 'R16', 'FIX_IN_PROGRESS', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-40', DATEADD('DAY', -39, CURRENT_TIMESTAMP), DATEADD('DAY', -37, CURRENT_TIMESTAMP), NULL, false),
('INC1041', 'PRB2041', 'PBT-3041', 'Issue in Auth Service - performance/outage #41', 'users reporting issues with Auth Service. Investigation required.', 42, 'Auth Service', 'Improved stability and user experience for Auth Service.', 'R', 11, 'R16', 'RESOLVED', 0.5, 2, 2, 'API_SYNCED', 'Root cause for ticket 41 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
(NULL, 'PRB2042', 'PBT-3042', 'Issue in Notification Service - performance/outage #42', 'users reporting issues with Notification Service. Investigation required.', 43, 'Notification Service', 'Improved stability and user experience for Notification Service.', 'P', 12, 'R16', 'CLOSED', 0.75, 3, 4, 'MANUAL_ENTRY', 'Root cause for ticket 42 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'App Support', NULL, DATEADD('HOUR', -3, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1043', 'PRB2043', 'PBT-3043', 'Issue in Search Index - performance/outage #43', 'users reporting issues with Search Index. Investigation required.', 44, 'Search Index', 'Improved stability and user experience for Search Index.', 'A', 13, 'R16', 'BACKLOG', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', NULL, DATEADD('DAY', -42, CURRENT_TIMESTAMP), DATEADD('DAY', -40, CURRENT_TIMESTAMP), NULL, false),
('INC1044', NULL, 'PBT-3044', 'Issue in API Gateway - performance/outage #44', 'users reporting issues with API Gateway. Investigation required.', 45, 'API Gateway', 'Improved stability and user experience for API Gateway.', 'R', 14, 'R16', 'ASSIGNED', 0.25, 1, 24, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -43, CURRENT_TIMESTAMP), DATEADD('DAY', -41, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2045', 'PBT-3045', 'Issue in Config Service - performance/outage #45', 'users reporting issues with Config Service. Investigation required.', 46, 'Config Service', 'Improved stability and user experience for Config Service.', 'P', 15, 'R16', 'IN_PROGRESS', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-45', DATEADD('DAY', -44, CURRENT_TIMESTAMP), DATEADD('DAY', -42, CURRENT_TIMESTAMP), NULL, false),
('INC1046', 'PRB2046', 'PBT-3046', 'Issue in Payment Gateway - performance/outage #46', 'users reporting issues with Payment Gateway. Investigation required.', 47, 'Payment Gateway', 'Improved stability and user experience for Payment Gateway.', 'A', 16, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -45, CURRENT_TIMESTAMP), DATEADD('DAY', -43, CURRENT_TIMESTAMP), NULL, false),
('INC1047', 'PRB2047', 'PBT-3047', 'Issue in Order Management - performance/outage #47', 'users reporting issues with Order Management. Investigation required.', 48, 'Order Management', 'Improved stability and user experience for Order Management.', 'R', 17, 'R16', 'FIX_IN_PROGRESS', 1.0, 4, 8, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -46, CURRENT_TIMESTAMP), DATEADD('DAY', -44, CURRENT_TIMESTAMP), NULL, false),
(NULL, NULL, 'PBT-3048', 'Issue in Inventory System - performance/outage #48', 'users reporting issues with Inventory System. Investigation required.', 49, 'Inventory System', 'Improved stability and user experience for Inventory System.', 'P', 18, 'R16', 'RESOLVED', 0.25, 1, 24, 'MANUAL_ENTRY', 'Root cause for ticket 48 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -47, CURRENT_TIMESTAMP), DATEADD('DAY', -45, CURRENT_TIMESTAMP), DATEADD('DAY', -42, CURRENT_TIMESTAMP), false),
('INC1049', 'PRB2049', 'PBT-3049', 'Issue in CRM - performance/outage #49', 'users reporting issues with CRM. Investigation required.', 50, 'CRM', 'Improved stability and user experience for CRM.', 'A', 19, 'R16', 'CLOSED', 0.5, 2, 2, 'MANUAL_ENTRY', 'Root cause for ticket 49 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1050', 'PRB2050', 'PBT-3050', 'Issue in HR Portal - performance/outage #50', 'users reporting issues with HR Portal. Investigation required.', 1, 'HR Portal', 'Improved stability and user experience for HR Portal.', 'R', 20, 'R16', 'BACKLOG', 0.75, 3, 4, 'API_SYNCED', NULL, NULL, NULL, 'admin', NULL, 'App Support', 'https://wiki.example.com/ticket-50', DATEADD('DAY', -49, CURRENT_TIMESTAMP), DATEADD('DAY', -47, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2051', 'PBT-3051', 'Issue in Finance Suite - performance/outage #51', 'users reporting issues with Finance Suite. Investigation required.', 2, 'Finance Suite', 'Improved stability and user experience for Finance Suite.', 'P', 21, 'R16', 'ASSIGNED', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -50, CURRENT_TIMESTAMP), DATEADD('DAY', -48, CURRENT_TIMESTAMP), NULL, false),
('INC1052', NULL, 'PBT-3052', 'Issue in Shipping Service - performance/outage #52', 'users reporting issues with Shipping Service. Investigation required.', 3, 'Shipping Service', 'Improved stability and user experience for Shipping Service.', 'A', 22, 'R16', 'IN_PROGRESS', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -51, CURRENT_TIMESTAMP), DATEADD('DAY', -49, CURRENT_TIMESTAMP), NULL, false),
('INC1053', 'PRB2053', 'PBT-3053', 'Issue in Customer Support - performance/outage #53', 'users reporting issues with Customer Support. Investigation required.', 4, 'Customer Support', 'Improved stability and user experience for Customer Support.', 'R', 23, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.5, 2, 2, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -52, CURRENT_TIMESTAMP), DATEADD('DAY', -50, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2054', 'PBT-3054', 'Issue in Analytics Dashboard - performance/outage #54', 'users reporting issues with Analytics Dashboard. Investigation required.', 5, 'Analytics Dashboard', 'Improved stability and user experience for Analytics Dashboard.', 'P', 24, 'R16', 'FIX_IN_PROGRESS', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -53, CURRENT_TIMESTAMP), DATEADD('DAY', -51, CURRENT_TIMESTAMP), NULL, false),
('INC1055', 'PRB2055', 'PBT-3055', 'Issue in Reporting Engine - performance/outage #55', 'users reporting issues with Reporting Engine. Investigation required.', 6, 'Reporting Engine', 'Improved stability and user experience for Reporting Engine.', 'A', 25, 'R16', 'RESOLVED', 1.0, 4, 8, 'MANUAL_ENTRY', 'Root cause for ticket 55 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-55', DATEADD('HOUR', -5, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1056', NULL, 'PBT-3056', 'Issue in Auth Service - performance/outage #56', 'users reporting issues with Auth Service. Investigation required.', 7, 'Auth Service', 'Improved stability and user experience for Auth Service.', 'R', 26, 'R16', 'CLOSED', 0.25, 1, 24, 'API_SYNCED', 'Root cause for ticket 56 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'App Support', NULL, DATEADD('HOUR', -20, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
(NULL, 'PRB2057', 'PBT-3057', 'Issue in Notification Service - performance/outage #57', 'users reporting issues with Notification Service. Investigation required.', 8, 'Notification Service', 'Improved stability and user experience for Notification Service.', 'P', 27, 'R16', 'BACKLOG', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', NULL, DATEADD('DAY', -56, CURRENT_TIMESTAMP), DATEADD('DAY', -54, CURRENT_TIMESTAMP), NULL, false),
('INC1058', 'PRB2058', 'PBT-3058', 'Issue in Search Index - performance/outage #58', 'users reporting issues with Search Index. Investigation required.', 9, 'Search Index', 'Improved stability and user experience for Search Index.', 'A', 28, 'R16', 'ASSIGNED', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -57, CURRENT_TIMESTAMP), DATEADD('DAY', -55, CURRENT_TIMESTAMP), NULL, false),
('INC1059', 'PRB2059', 'PBT-3059', 'Issue in API Gateway - performance/outage #59', 'users reporting issues with API Gateway. Investigation required.', 10, 'API Gateway', 'Improved stability and user experience for API Gateway.', 'R', 29, 'R16', 'IN_PROGRESS', 1.0, 4, 8, 'API_SYNCED', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -58, CURRENT_TIMESTAMP), DATEADD('DAY', -56, CURRENT_TIMESTAMP), NULL, false),
(NULL, NULL, 'PBT-3060', 'Issue in Config Service - performance/outage #60', 'users reporting issues with Config Service. Investigation required.', 11, 'Config Service', 'Improved stability and user experience for Config Service.', 'P', 0, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-60', DATEADD('DAY', -59, CURRENT_TIMESTAMP), DATEADD('DAY', -57, CURRENT_TIMESTAMP), NULL, false),
('INC1061', 'PRB2061', 'PBT-3061', 'Issue in Payment Gateway - performance/outage #61', 'users reporting issues with Payment Gateway. Investigation required.', 12, 'Payment Gateway', 'Improved stability and user experience for Payment Gateway.', 'A', 1, 'R16', 'FIX_IN_PROGRESS', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -60, CURRENT_TIMESTAMP), DATEADD('DAY', -58, CURRENT_TIMESTAMP), NULL, false),
('INC1062', 'PRB2062', 'PBT-3062', 'Issue in Order Management - performance/outage #62', 'users reporting issues with Order Management. Investigation required.', 13, 'Order Management', 'Improved stability and user experience for Order Management.', 'R', 2, 'R16', 'RESOLVED', 0.75, 3, 4, 'API_SYNCED', 'Root cause for ticket 62 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -61, CURRENT_TIMESTAMP), DATEADD('DAY', -59, CURRENT_TIMESTAMP), DATEADD('DAY', -56, CURRENT_TIMESTAMP), false),
(NULL, 'PRB2063', 'PBT-3063', 'Issue in Inventory System - performance/outage #63', 'users reporting issues with Inventory System. Investigation required.', 14, 'Inventory System', 'Improved stability and user experience for Inventory System.', 'P', 3, 'R16', 'CLOSED', 1.0, 4, 8, 'MANUAL_ENTRY', 'Root cause for ticket 63 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -62, CURRENT_TIMESTAMP), DATEADD('DAY', -60, CURRENT_TIMESTAMP), DATEADD('DAY', -57, CURRENT_TIMESTAMP), false),
('INC1064', NULL, 'PBT-3064', 'Issue in CRM - performance/outage #64', 'users reporting issues with CRM. Investigation required.', 15, 'CRM', 'Improved stability and user experience for CRM.', 'A', 4, 'R16', 'BACKLOG', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'App Support', NULL, DATEADD('DAY', -63, CURRENT_TIMESTAMP), DATEADD('DAY', -61, CURRENT_TIMESTAMP), NULL, false),
('INC1065', 'PRB2065', 'PBT-3065', 'Issue in HR Portal - performance/outage #65', 'users reporting issues with HR Portal. Investigation required.', 16, 'HR Portal', 'Improved stability and user experience for HR Portal.', 'R', 5, 'R16', 'ASSIGNED', 0.5, 2, 2, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-65', DATEADD('DAY', -64, CURRENT_TIMESTAMP), DATEADD('DAY', -62, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2066', 'PBT-3066', 'Issue in Finance Suite - performance/outage #66', 'users reporting issues with Finance Suite. Investigation required.', 17, 'Finance Suite', 'Improved stability and user experience for Finance Suite.', 'P', 6, 'R16', 'IN_PROGRESS', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -65, CURRENT_TIMESTAMP), DATEADD('DAY', -63, CURRENT_TIMESTAMP), NULL, false),
('INC1067', 'PRB2067', 'PBT-3067', 'Issue in Shipping Service - performance/outage #67', 'users reporting issues with Shipping Service. Investigation required.', 18, 'Shipping Service', 'Improved stability and user experience for Shipping Service.', 'A', 7, 'R16', 'ROOT_CAUSE_IDENTIFIED', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -66, CURRENT_TIMESTAMP), DATEADD('DAY', -64, CURRENT_TIMESTAMP), NULL, false),
('INC1068', NULL, 'PBT-3068', 'Issue in Customer Support - performance/outage #68', 'users reporting issues with Customer Support. Investigation required.', 19, 'Customer Support', 'Improved stability and user experience for Customer Support.', 'R', 8, 'R16', 'FIX_IN_PROGRESS', 0.25, 1, 24, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -67, CURRENT_TIMESTAMP), DATEADD('DAY', -65, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2069', 'PBT-3069', 'Issue in Analytics Dashboard - performance/outage #69', 'users reporting issues with Analytics Dashboard. Investigation required.', 20, 'Analytics Dashboard', 'Improved stability and user experience for Analytics Dashboard.', 'P', 9, 'R16', 'RESOLVED', 0.5, 2, 2, 'MANUAL_ENTRY', 'Root cause for ticket 69 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -68, CURRENT_TIMESTAMP), DATEADD('DAY', -66, CURRENT_TIMESTAMP), DATEADD('DAY', -63, CURRENT_TIMESTAMP), false),
('INC1070', 'PRB2070', 'PBT-3070', 'Issue in Reporting Engine - performance/outage #70', 'users reporting issues with Reporting Engine. Investigation required.', 21, 'Reporting Engine', 'Improved stability and user experience for Reporting Engine.', 'A', 10, 'R16', 'CLOSED', 0.75, 3, 4, 'MANUAL_ENTRY', 'Root cause for ticket 70 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-70', DATEADD('HOUR', -2, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1071', 'PRB2071', 'PBT-3071', 'Issue in Auth Service - performance/outage #71', 'users reporting issues with Auth Service. Investigation required.', 22, 'Auth Service', 'Improved stability and user experience for Auth Service.', 'R', 11, 'R16', 'BACKLOG', 1.0, 4, 8, 'API_SYNCED', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', NULL, DATEADD('DAY', -70, CURRENT_TIMESTAMP), DATEADD('DAY', -68, CURRENT_TIMESTAMP), NULL, false),
(NULL, NULL, 'PBT-3072', 'Issue in Notification Service - performance/outage #72', 'users reporting issues with Notification Service. Investigation required.', 23, 'Notification Service', 'Improved stability and user experience for Notification Service.', 'P', 12, 'R16', 'ASSIGNED', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -71, CURRENT_TIMESTAMP), DATEADD('DAY', -69, CURRENT_TIMESTAMP), NULL, false),
('INC1073', 'PRB2073', 'PBT-3073', 'Issue in Search Index - performance/outage #73', 'users reporting issues with Search Index. Investigation required.', 24, 'Search Index', 'Improved stability and user experience for Search Index.', 'A', 13, 'R16', 'IN_PROGRESS', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -72, CURRENT_TIMESTAMP), DATEADD('DAY', -70, CURRENT_TIMESTAMP), NULL, false),
('INC1074', 'PRB2074', 'PBT-3074', 'Issue in API Gateway - performance/outage #74', 'users reporting issues with API Gateway. Investigation required.', 25, 'API Gateway', 'Improved stability and user experience for API Gateway.', 'R', 14, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.75, 3, 4, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -73, CURRENT_TIMESTAMP), DATEADD('DAY', -71, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2075', 'PBT-3075', 'Issue in Config Service - performance/outage #75', 'users reporting issues with Config Service. Investigation required.', 26, 'Config Service', 'Improved stability and user experience for Config Service.', 'P', 15, 'R16', 'FIX_IN_PROGRESS', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-75', DATEADD('DAY', -74, CURRENT_TIMESTAMP), DATEADD('DAY', -72, CURRENT_TIMESTAMP), NULL, false),
('INC1076', NULL, 'PBT-3076', 'Issue in Payment Gateway - performance/outage #76', 'users reporting issues with Payment Gateway. Investigation required.', 27, 'Payment Gateway', 'Improved stability and user experience for Payment Gateway.', 'A', 16, 'R16', 'RESOLVED', 0.25, 1, 24, 'MANUAL_ENTRY', 'Root cause for ticket 76 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('HOUR', -20, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1077', 'PRB2077', 'PBT-3077', 'Issue in Order Management - performance/outage #77', 'users reporting issues with Order Management. Investigation required.', 28, 'Order Management', 'Improved stability and user experience for Order Management.', 'R', 17, 'R16', 'CLOSED', 0.5, 2, 2, 'API_SYNCED', 'Root cause for ticket 77 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
(NULL, 'PRB2078', 'PBT-3078', 'Issue in Inventory System - performance/outage #78', 'users reporting issues with Inventory System. Investigation required.', 29, 'Inventory System', 'Improved stability and user experience for Inventory System.', 'P', 18, 'R16', 'BACKLOG', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'App Support', NULL, DATEADD('DAY', -77, CURRENT_TIMESTAMP), DATEADD('DAY', -75, CURRENT_TIMESTAMP), NULL, false),
('INC1079', 'PRB2079', 'PBT-3079', 'Issue in CRM - performance/outage #79', 'users reporting issues with CRM. Investigation required.', 30, 'CRM', 'Improved stability and user experience for CRM.', 'A', 19, 'R16', 'ASSIGNED', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -78, CURRENT_TIMESTAMP), DATEADD('DAY', -76, CURRENT_TIMESTAMP), NULL, false),
('INC1080', NULL, 'PBT-3080', 'Issue in HR Portal - performance/outage #80', 'users reporting issues with HR Portal. Investigation required.', 31, 'HR Portal', 'Improved stability and user experience for HR Portal.', 'R', 20, 'R16', 'IN_PROGRESS', 0.25, 1, 24, 'API_SYNCED', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-80', DATEADD('DAY', -79, CURRENT_TIMESTAMP), DATEADD('DAY', -77, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2081', 'PBT-3081', 'Issue in Finance Suite - performance/outage #81', 'users reporting issues with Finance Suite. Investigation required.', 32, 'Finance Suite', 'Improved stability and user experience for Finance Suite.', 'P', 21, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -80, CURRENT_TIMESTAMP), DATEADD('DAY', -78, CURRENT_TIMESTAMP), NULL, false),
('INC1082', 'PRB2082', 'PBT-3082', 'Issue in Shipping Service - performance/outage #82', 'users reporting issues with Shipping Service. Investigation required.', 33, 'Shipping Service', 'Improved stability and user experience for Shipping Service.', 'A', 22, 'R16', 'FIX_IN_PROGRESS', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -81, CURRENT_TIMESTAMP), DATEADD('DAY', -79, CURRENT_TIMESTAMP), NULL, false),
('INC1083', 'PRB2083', 'PBT-3083', 'Issue in Customer Support - performance/outage #83', 'users reporting issues with Customer Support. Investigation required.', 34, 'Customer Support', 'Improved stability and user experience for Customer Support.', 'R', 23, 'R16', 'RESOLVED', 1.0, 4, 8, 'API_SYNCED', 'Root cause for ticket 83 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -82, CURRENT_TIMESTAMP), DATEADD('DAY', -80, CURRENT_TIMESTAMP), DATEADD('DAY', -77, CURRENT_TIMESTAMP), false),
(NULL, NULL, 'PBT-3084', 'Issue in Analytics Dashboard - performance/outage #84', 'users reporting issues with Analytics Dashboard. Investigation required.', 35, 'Analytics Dashboard', 'Improved stability and user experience for Analytics Dashboard.', 'P', 24, 'R16', 'CLOSED', 0.25, 1, 24, 'MANUAL_ENTRY', 'Root cause for ticket 84 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -83, CURRENT_TIMESTAMP), DATEADD('DAY', -81, CURRENT_TIMESTAMP), DATEADD('DAY', -78, CURRENT_TIMESTAMP), false),
('INC1085', 'PRB2085', 'PBT-3085', 'Issue in Reporting Engine - performance/outage #85', 'users reporting issues with Reporting Engine. Investigation required.', 36, 'Reporting Engine', 'Improved stability and user experience for Reporting Engine.', 'A', 25, 'R16', 'BACKLOG', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', 'https://wiki.example.com/ticket-85', DATEADD('DAY', -84, CURRENT_TIMESTAMP), DATEADD('DAY', -82, CURRENT_TIMESTAMP), NULL, false),
('INC1086', 'PRB2086', 'PBT-3086', 'Issue in Auth Service - performance/outage #86', 'users reporting issues with Auth Service. Investigation required.', 37, 'Auth Service', 'Improved stability and user experience for Auth Service.', 'R', 26, 'R16', 'ASSIGNED', 0.75, 3, 4, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -85, CURRENT_TIMESTAMP), DATEADD('DAY', -83, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2087', 'PBT-3087', 'Issue in Notification Service - performance/outage #87', 'users reporting issues with Notification Service. Investigation required.', 38, 'Notification Service', 'Improved stability and user experience for Notification Service.', 'P', 27, 'R16', 'IN_PROGRESS', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -86, CURRENT_TIMESTAMP), DATEADD('DAY', -84, CURRENT_TIMESTAMP), NULL, false),
('INC1088', NULL, 'PBT-3088', 'Issue in Search Index - performance/outage #88', 'users reporting issues with Search Index. Investigation required.', 39, 'Search Index', 'Improved stability and user experience for Search Index.', 'A', 28, 'R16', 'ROOT_CAUSE_IDENTIFIED', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -87, CURRENT_TIMESTAMP), DATEADD('DAY', -85, CURRENT_TIMESTAMP), NULL, false),
('INC1089', 'PRB2089', 'PBT-3089', 'Issue in API Gateway - performance/outage #89', 'users reporting issues with API Gateway. Investigation required.', 40, 'API Gateway', 'Improved stability and user experience for API Gateway.', 'R', 29, 'R16', 'FIX_IN_PROGRESS', 0.5, 2, 2, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -88, CURRENT_TIMESTAMP), DATEADD('DAY', -86, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2090', 'PBT-3090', 'Issue in Config Service - performance/outage #90', 'users reporting issues with Config Service. Investigation required.', 41, 'Config Service', 'Improved stability and user experience for Config Service.', 'P', 0, 'R16', 'RESOLVED', 0.75, 3, 4, 'MANUAL_ENTRY', 'Root cause for ticket 90 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-90', DATEADD('HOUR', -3, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1091', 'PRB2091', 'PBT-3091', 'Issue in Payment Gateway - performance/outage #91', 'users reporting issues with Payment Gateway. Investigation required.', 42, 'Payment Gateway', 'Improved stability and user experience for Payment Gateway.', 'A', 1, 'R16', 'CLOSED', 1.0, 4, 8, 'MANUAL_ENTRY', 'Root cause for ticket 91 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'Platform Team', NULL, DATEADD('HOUR', -6, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), DATEADD('HOUR', -0, CURRENT_TIMESTAMP), false),
('INC1092', NULL, 'PBT-3092', 'Issue in Order Management - performance/outage #92', 'users reporting issues with Order Management. Investigation required.', 43, 'Order Management', 'Improved stability and user experience for Order Management.', 'R', 2, 'R16', 'BACKLOG', 0.25, 1, 24, 'API_SYNCED', NULL, NULL, NULL, 'admin', NULL, 'App Support', NULL, DATEADD('DAY', -91, CURRENT_TIMESTAMP), DATEADD('DAY', -89, CURRENT_TIMESTAMP), NULL, false),
(NULL, 'PRB2093', 'PBT-3093', 'Issue in Inventory System - performance/outage #93', 'users reporting issues with Inventory System. Investigation required.', 44, 'Inventory System', 'Improved stability and user experience for Inventory System.', 'P', 3, 'R16', 'ASSIGNED', 0.5, 2, 2, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -92, CURRENT_TIMESTAMP), DATEADD('DAY', -90, CURRENT_TIMESTAMP), NULL, false),
('INC1094', 'PRB2094', 'PBT-3094', 'Issue in CRM - performance/outage #94', 'users reporting issues with CRM. Investigation required.', 45, 'CRM', 'Improved stability and user experience for CRM.', 'A', 4, 'R16', 'IN_PROGRESS', 0.75, 3, 4, 'MANUAL_ENTRY', NULL, 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -93, CURRENT_TIMESTAMP), DATEADD('DAY', -91, CURRENT_TIMESTAMP), NULL, false),
('INC1095', 'PRB2095', 'PBT-3095', 'Issue in HR Portal - performance/outage #95', 'users reporting issues with HR Portal. Investigation required.', 46, 'HR Portal', 'Improved stability and user experience for HR Portal.', 'R', 5, 'R16', 'ROOT_CAUSE_IDENTIFIED', 1.0, 4, 8, 'API_SYNCED', NULL, NULL, NULL, 'admin', 'admin', 'Platform Team', 'https://wiki.example.com/ticket-95', DATEADD('DAY', -94, CURRENT_TIMESTAMP), DATEADD('DAY', -92, CURRENT_TIMESTAMP), NULL, false),
(NULL, NULL, 'PBT-3096', 'Issue in Finance Suite - performance/outage #96', 'users reporting issues with Finance Suite. Investigation required.', 47, 'Finance Suite', 'Improved stability and user experience for Finance Suite.', 'P', 6, 'R16', 'FIX_IN_PROGRESS', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -95, CURRENT_TIMESTAMP), DATEADD('DAY', -93, CURRENT_TIMESTAMP), NULL, false),
('INC1097', 'PRB2097', 'PBT-3097', 'Issue in Shipping Service - performance/outage #97', 'users reporting issues with Shipping Service. Investigation required.', 48, 'Shipping Service', 'Improved stability and user experience for Shipping Service.', 'A', 7, 'R16', 'RESOLVED', 0.5, 2, 2, 'MANUAL_ENTRY', 'Root cause for ticket 97 (config or dependency).', 'Workaround: use alternate endpoint or retry.', NULL, 'admin', 'admin', 'Platform Team', NULL, DATEADD('DAY', -96, CURRENT_TIMESTAMP), DATEADD('DAY', -94, CURRENT_TIMESTAMP), DATEADD('DAY', -91, CURRENT_TIMESTAMP), false),
('INC1098', 'PRB2098', 'PBT-3098', 'Issue in Customer Support - performance/outage #98', 'users reporting issues with Customer Support. Investigation required.', 49, 'Customer Support', 'Improved stability and user experience for Customer Support.', 'R', 8, 'R16', 'CLOSED', 0.75, 3, 4, 'API_SYNCED', 'Root cause for ticket 98 (config or dependency).', 'Workaround: use alternate endpoint or retry.', 'Permanent fix deployed.', 'admin', 'admin', 'App Support', NULL, DATEADD('DAY', -97, CURRENT_TIMESTAMP), DATEADD('DAY', -95, CURRENT_TIMESTAMP), DATEADD('DAY', -92, CURRENT_TIMESTAMP), false),
(NULL, 'PRB2099', 'PBT-3099', 'Issue in Analytics Dashboard - performance/outage #99', 'users reporting issues with Analytics Dashboard. Investigation required.', 50, 'Analytics Dashboard', 'Improved stability and user experience for Analytics Dashboard.', 'P', 9, 'R16', 'BACKLOG', 1.0, 4, 8, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', NULL, 'Platform Team', NULL, DATEADD('DAY', -98, CURRENT_TIMESTAMP), DATEADD('DAY', -96, CURRENT_TIMESTAMP), NULL, false),
('INC1100', NULL, 'PBT-3100', 'Issue in Reporting Engine - performance/outage #100', 'users reporting issues with Reporting Engine. Investigation required.', 1, 'Reporting Engine', 'Improved stability and user experience for Reporting Engine.', 'A', 10, 'R16', 'ASSIGNED', 0.25, 1, 24, 'MANUAL_ENTRY', NULL, NULL, NULL, 'admin', 'admin', 'App Support', 'https://wiki.example.com/ticket-100', DATEADD('DAY', -99, CURRENT_TIMESTAMP), DATEADD('DAY', -97, CURRENT_TIMESTAMP), NULL, false)
;

INSERT INTO fast_problem_region (fast_problem_id, regional_code) VALUES
(1, 'EMEA'),
(1, 'AMER'),
(2, 'AMER'),
(2, 'APAC'),
(2, 'EMEA'),
(3, 'APAC'),
(4, 'EMEA'),
(4, 'AMER'),
(5, 'AMER'),
(5, 'APAC'),
(5, 'EMEA'),
(6, 'APAC'),
(7, 'EMEA'),
(7, 'AMER'),
(8, 'AMER'),
(8, 'APAC'),
(8, 'EMEA'),
(9, 'APAC'),
(10, 'EMEA'),
(10, 'AMER'),
(11, 'AMER'),
(11, 'APAC'),
(11, 'EMEA'),
(12, 'APAC'),
(13, 'EMEA'),
(13, 'AMER'),
(14, 'AMER'),
(14, 'APAC'),
(14, 'EMEA'),
(15, 'APAC'),
(16, 'EMEA'),
(16, 'AMER'),
(17, 'AMER'),
(17, 'APAC'),
(17, 'EMEA'),
(18, 'APAC'),
(19, 'EMEA'),
(19, 'AMER'),
(20, 'AMER'),
(20, 'APAC'),
(20, 'EMEA'),
(21, 'APAC'),
(22, 'EMEA'),
(22, 'AMER'),
(23, 'AMER'),
(23, 'APAC'),
(23, 'EMEA'),
(24, 'APAC'),
(25, 'EMEA'),
(25, 'AMER'),
(26, 'AMER'),
(26, 'APAC'),
(26, 'EMEA'),
(27, 'APAC'),
(28, 'EMEA'),
(28, 'AMER'),
(29, 'AMER'),
(29, 'APAC'),
(29, 'EMEA'),
(30, 'APAC'),
(31, 'EMEA'),
(31, 'AMER'),
(32, 'AMER'),
(32, 'APAC'),
(32, 'EMEA'),
(33, 'APAC'),
(34, 'EMEA'),
(34, 'AMER'),
(35, 'AMER'),
(35, 'APAC'),
(35, 'EMEA'),
(36, 'APAC'),
(37, 'EMEA'),
(37, 'AMER'),
(38, 'AMER'),
(38, 'APAC'),
(38, 'EMEA'),
(39, 'APAC'),
(40, 'EMEA'),
(40, 'AMER'),
(41, 'AMER'),
(41, 'APAC'),
(41, 'EMEA'),
(42, 'APAC'),
(43, 'EMEA'),
(43, 'AMER'),
(44, 'AMER'),
(44, 'APAC'),
(44, 'EMEA'),
(45, 'APAC'),
(46, 'EMEA'),
(46, 'AMER'),
(47, 'AMER'),
(47, 'APAC'),
(47, 'EMEA'),
(48, 'APAC'),
(49, 'EMEA'),
(49, 'AMER'),
(50, 'AMER'),
(50, 'APAC'),
(50, 'EMEA'),
(51, 'APAC'),
(52, 'EMEA'),
(52, 'AMER'),
(53, 'AMER'),
(53, 'APAC'),
(53, 'EMEA'),
(54, 'APAC'),
(55, 'EMEA'),
(55, 'AMER'),
(56, 'AMER'),
(56, 'APAC'),
(56, 'EMEA'),
(57, 'APAC'),
(58, 'EMEA'),
(58, 'AMER'),
(59, 'AMER'),
(59, 'APAC'),
(59, 'EMEA'),
(60, 'APAC'),
(61, 'EMEA'),
(61, 'AMER'),
(62, 'AMER'),
(62, 'APAC'),
(62, 'EMEA'),
(63, 'APAC'),
(64, 'EMEA'),
(64, 'AMER'),
(65, 'AMER'),
(65, 'APAC'),
(65, 'EMEA'),
(66, 'APAC'),
(67, 'EMEA'),
(67, 'AMER'),
(68, 'AMER'),
(68, 'APAC'),
(68, 'EMEA'),
(69, 'APAC'),
(70, 'EMEA'),
(70, 'AMER'),
(71, 'AMER'),
(71, 'APAC'),
(71, 'EMEA'),
(72, 'APAC'),
(73, 'EMEA'),
(73, 'AMER'),
(74, 'AMER'),
(74, 'APAC'),
(74, 'EMEA'),
(75, 'APAC'),
(76, 'EMEA'),
(76, 'AMER'),
(77, 'AMER'),
(77, 'APAC'),
(77, 'EMEA'),
(78, 'APAC'),
(79, 'EMEA'),
(79, 'AMER'),
(80, 'AMER'),
(80, 'APAC'),
(80, 'EMEA'),
(81, 'APAC'),
(82, 'EMEA'),
(82, 'AMER'),
(83, 'AMER'),
(83, 'APAC'),
(83, 'EMEA'),
(84, 'APAC'),
(85, 'EMEA'),
(85, 'AMER'),
(86, 'AMER'),
(86, 'APAC'),
(86, 'EMEA'),
(87, 'APAC'),
(88, 'EMEA'),
(88, 'AMER'),
(89, 'AMER'),
(89, 'APAC'),
(89, 'EMEA'),
(90, 'APAC'),
(91, 'EMEA'),
(91, 'AMER'),
(92, 'AMER'),
(92, 'APAC'),
(92, 'EMEA'),
(93, 'APAC'),
(94, 'EMEA'),
(94, 'AMER'),
(95, 'AMER'),
(95, 'APAC'),
(95, 'EMEA'),
(96, 'APAC'),
(97, 'EMEA'),
(97, 'AMER'),
(98, 'AMER'),
(98, 'APAC'),
(98, 'EMEA'),
(99, 'APAC'),
(100, 'EMEA'),
(100, 'AMER')
;

-- RAG status based on ticket_age_days: G ≤15, A 15–20, R >20 (for demo/testing varied chart data)
UPDATE fast_problem SET rag_status = 'A' WHERE ticket_age_days > 15 AND ticket_age_days <= 20 AND deleted = false;
UPDATE fast_problem SET rag_status = 'R' WHERE ticket_age_days > 20 AND deleted = false;

-- Archived status: set some CLOSED tickets to ARCHIVED for demo (status + archived flag)
UPDATE fast_problem SET status = 'ARCHIVED', archived = true, closed_date = COALESCE(closed_date, DATEADD('DAY', -10, CURRENT_TIMESTAMP)) WHERE id IN (7, 14, 21, 28, 35, 42, 49, 56) AND deleted = false;
