-- =============================================================================
-- FAST - Oracle Database Master Setup Script
-- Fast Acceleration Support Team - Enterprise Problem Management
-- Run as schema owner. Requires Oracle 12c+ (for IDENTITY columns).
--
-- Application: set spring.datasource.url to Oracle JDBC and
-- spring.jpa.database-platform=org.hibernate.dialect.OracleDialect.
-- Some dashboard metrics use TIMESTAMPDIFF (H2/MySQL); replace with
-- Oracle equivalent if running metrics queries natively on Oracle.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. USERS
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50) NOT NULL,
    password        VARCHAR2(255),
    email           VARCHAR2(100) NOT NULL,
    full_name       VARCHAR2(100) NOT NULL,
    role            VARCHAR2(30) NOT NULL,
    region          VARCHAR2(10),
    active          NUMBER(1) DEFAULT 1 NOT NULL,
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    brid            VARCHAR2(20),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_brid UNIQUE (brid),
    CONSTRAINT chk_users_active CHECK (active IN (0, 1))
);

CREATE INDEX idx_users_active ON users(active);

-- -----------------------------------------------------------------------------
-- 2. FAST_PROBLEM
-- -----------------------------------------------------------------------------
CREATE TABLE fast_problem (
    id                          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    servicenow_incident_number  VARCHAR2(20),
    servicenow_problem_number   VARCHAR2(20),
    pbt_id                      VARCHAR2(30),
    title                       VARCHAR2(255) NOT NULL,
    description                 CLOB,
    user_impact_count           NUMBER(10) DEFAULT 0,
    affected_application       VARCHAR2(100),
    anticipated_benefits        CLOB,
    classification              VARCHAR2(10) DEFAULT 'A',
    regional_code               VARCHAR2(10) NOT NULL,
    ticket_age_days             NUMBER(10) DEFAULT 0,
    status_indicator            VARCHAR2(10) DEFAULT 'R16',
    status                      VARCHAR2(30) DEFAULT 'NEW',
    priority_score              BINARY_DOUBLE DEFAULT 0.0,
    priority                    NUMBER(10) DEFAULT 3,
    target_resolution_hours     NUMBER(10) DEFAULT 4,
    api_integration_status      VARCHAR2(20) DEFAULT 'MANUAL_ENTRY',
    root_cause                  CLOB,
    workaround                  CLOB,
    permanent_fix               CLOB,
    created_by                  VARCHAR2(50) NOT NULL,
    assigned_to                 VARCHAR2(50),
    assignment_group            VARCHAR2(100),
    confluence_link             VARCHAR2(500),
    created_date                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_date               TIMESTAMP,
    deleted                     NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_fast_problem_deleted CHECK (deleted IN (0, 1))
);

CREATE INDEX idx_fast_problem_status ON fast_problem(status);
CREATE INDEX idx_fast_problem_classification ON fast_problem(classification);
CREATE INDEX idx_fast_problem_regional_code ON fast_problem(regional_code);
CREATE INDEX idx_fast_problem_pbt_id ON fast_problem(pbt_id);
CREATE INDEX idx_fast_problem_inc_number ON fast_problem(servicenow_incident_number);
CREATE INDEX idx_fast_problem_prb_number ON fast_problem(servicenow_problem_number);
CREATE INDEX idx_fast_problem_created_date ON fast_problem(created_date);
CREATE INDEX idx_fast_problem_deleted ON fast_problem(deleted);
CREATE INDEX idx_fast_problem_deleted_created ON fast_problem(deleted, created_date);
CREATE INDEX idx_fast_problem_affected_app ON fast_problem(affected_application);

-- -----------------------------------------------------------------------------
-- 3. APPROVAL_RECORD
-- -----------------------------------------------------------------------------
CREATE TABLE approval_record (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    reviewer_name   VARCHAR2(100) NOT NULL,
    reviewer_email  VARCHAR2(100),
    decision        VARCHAR2(20) DEFAULT 'PENDING',
    comments        CLOB,
    decision_date   TIMESTAMP,
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_approval_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);

CREATE INDEX idx_approval_problem_id ON approval_record(fast_problem_id);
CREATE INDEX idx_approval_decision ON approval_record(decision);

-- -----------------------------------------------------------------------------
-- 4. KNOWLEDGE_ARTICLE
-- -----------------------------------------------------------------------------
CREATE TABLE knowledge_article (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19),
    title           VARCHAR2(255) NOT NULL,
    root_cause      CLOB,
    workaround      CLOB,
    permanent_fix   CLOB,
    category        VARCHAR2(50),
    status          VARCHAR2(20) DEFAULT 'DRAFT',
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    published_date  TIMESTAMP,
    CONSTRAINT uq_knowledge_fast_problem_id UNIQUE (fast_problem_id),
    CONSTRAINT fk_knowledge_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);

CREATE INDEX idx_knowledge_status ON knowledge_article(status);
CREATE INDEX idx_knowledge_created_date ON knowledge_article(created_date);

-- -----------------------------------------------------------------------------
-- 5. INCIDENT_LINK
-- -----------------------------------------------------------------------------
CREATE TABLE incident_link (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    incident_number VARCHAR2(20) NOT NULL,
    link_type       VARCHAR2(20) DEFAULT 'RELATED_TO',
    description     VARCHAR2(500),
    linked_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_incident_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);

CREATE INDEX idx_incident_link_problem_id ON incident_link(fast_problem_id);
CREATE INDEX idx_incident_link_number ON incident_link(incident_number);

-- -----------------------------------------------------------------------------
-- 6. AUDIT_LOG
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fast_problem_id NUMBER(19) NOT NULL,
    action          VARCHAR2(50) NOT NULL,
    performed_by    VARCHAR2(50) NOT NULL,
    field_changed   VARCHAR2(50),
    old_value       VARCHAR2(500),
    new_value       VARCHAR2(500),
    timestamp       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_problem FOREIGN KEY (fast_problem_id) REFERENCES fast_problem(id)
);

CREATE INDEX idx_audit_problem_id ON audit_log(fast_problem_id);
CREATE INDEX idx_audit_timestamp ON audit_log(timestamp);
CREATE INDEX idx_audit_problem_timestamp ON audit_log(fast_problem_id, timestamp);

-- -----------------------------------------------------------------------------
-- Optional: Sequences for Oracle 11g (if not using IDENTITY)
-- Uncomment if you need Oracle 11g compatibility and replace IDENTITY with
-- trigger-based sequence assignment.
-- -----------------------------------------------------------------------------
-- CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE fast_problem_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- ... etc.

COMMIT;
